model: A
temperature: 0.7
max_tokens: 16384
description: |
  I'm here to help refine your system prompt. 
  You can ask me to create, modify, or enhance your prompt. 
  Just share your prompt, and we can discuss it further.
__buildin__: true