model: gpt-4o
temperature: 0.7
description: |
  Hi, I'm your casual assistant.
  How can I help you today?
#tools:
#  - wolfram_alpha

contexts:
  string: We are located in Poland
  file: ./../about_me.txt