model: A
temperature: 0.7
max_tokens: 4096
description: |
  Hi, I'm your casual assistant.
  How can I help you today?
tools:
  - text-to-image
  - vector-search
  - audio-to-text
  - text-to-text
  - image-analysis
#  - wolfram_alpha
#  - brave_web
__buildin__: true