name: Build Standalone Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

env:
  APP_NAME: kraina

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get install -y \
            python3.12 \
            python3.12-venv \
            python3.12-dev \
            python3-pip \
            pkg-config \
            python3.12-tk \
            tk-dev \
            libdbus-1-dev \
            libglib2.0-dev
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

      - name: Create virtual environment
        run: |
          python -m venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          # Pin contrib hooks to match local version for consistency
          pip install pyinstaller-hooks-contrib==2025.5
          pip install -e .
          pip install pyinstaller

      - name: Build standalone executables
        run: |
          chmod +x build_standalone.sh
          ./build_standalone.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kraina-linux-x64
          path: |
            dist/kraina_app
            dist/kraina_cli
          retention-days: 30

  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv .venv

      - name: Install dependencies
        run: |
          .venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install pyinstaller-hooks-contrib==2025.5
          pip install -e .
          pip install pyinstaller

      - name: Build standalone executables
        run: |
          .venv\Scripts\activate
          .\build_standalone.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kraina-windows-x64
          path: |
            dist/kraina_app.exe
            dist/kraina_cli.exe
          retention-days: 30

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: kraina-linux-x64
          path: artifacts/linux

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: kraina-windows-x64
          path: artifacts/windows

      - name: Display structure of downloaded files
        run: |
          ls -la artifacts/
          find artifacts/ -type f -exec ls -lh {} \;

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux/kraina_app
            artifacts/linux/kraina_cli
            artifacts/windows/kraina_app.exe
            artifacts/windows/kraina_cli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 